include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    avoid_catches_without_on_clauses: false
    avoid_print: true
    cascade_invocations: false
    eol_at_end_of_file: false
    flutter_style_todos: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_final_locals: true
    prefer_int_literals: false
    public_member_api_docs: false
    sort_constructors_first: true
    sort_pub_dependencies: false
    unawaited_futures: true
    unnecessary_lambdas: false
    unnecessary_raw_strings: false
    use_key_in_widget_constructors: true
    use_super_parameters: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
    
  errors:
    invalid_annotation_target: ignore
    missing_return: error
    dead_code: warning
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/firebase_options.dart"