// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgUWhGaCJ_c3JHi5475cCDceVyxZ8ESDw',
    appId: '1:473909583455:web:f3048685f19918dc1345ea',
    messagingSenderId: '473909583455',
    projectId: 'chat-app-695f9',
    authDomain: 'chat-app-695f9.firebaseapp.com',
    storageBucket: 'chat-app-695f9.firebasestorage.app',
    measurementId: 'G-E72HZ3REL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrohjoKhUgaDrIInBv7seON2D48eQSvI',
    appId: '1:473909583455:android:19f84abe57e1ff3a1345ea',
    messagingSenderId: '473909583455',
    projectId: 'chat-app-695f9',
    storageBucket: 'chat-app-695f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtSCpUTeyENUQ-yOoHxEjB-PVyc0xeksg',
    appId: '1:473909583455:ios:7a3cb5280aa224431345ea',
    messagingSenderId: '473909583455',
    projectId: 'chat-app-695f9',
    storageBucket: 'chat-app-695f9.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );
}
