// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClWXgPR6NqMlA_RMYKzv_TzjAYnCGTWSw',
    appId: '1:921498073331:web:f3048685f19918dc1345ea',
    messagingSenderId: '921498073331',
    projectId: 'our-chat-7fe22',
    authDomain: 'our-chat-7fe22.firebaseapp.com',
    storageBucket: 'our-chat-7fe22.firebasestorage.app',
    measurementId: 'G-E72HZ3REL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWXgPR6NqMlA_RMYKzv_TzjAYnCGTWSw',
    appId: '1:921498073331:android:02be157b537e2f69615f86',
    messagingSenderId: '921498073331',
    projectId: 'our-chat-7fe22',
    storageBucket: 'our-chat-7fe22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClWXgPR6NqMlA_RMYKzv_TzjAYnCGTWSw',
    appId: '1:921498073331:ios:7a3cb5280aa224431345ea',
    messagingSenderId: '921498073331',
    projectId: 'our-chat-7fe22',
    storageBucket: 'our-chat-7fe22.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );
}
